### ISSUE TITLE
Tests break on 2.13 branch for Python 2.6

### ISSUE THREAD

**Issue by icemac** [zopefoundation/DocumentTemplate#14]
See https://travis-ci.org/zopefoundation/DocumentTemplate/jobs/309970718

Maybe it is enough to use an old enough zc.buildout version.

**Comment by hannosch** [comment]
See zopefoundation/Zope#230 for a potential solution with changes to the travis.yml file

**Comment by icemac** [comment]
@hannosch Thank you for the pointer.
