### ISSUE TITLE
<dtml-in list_of_dicts mapping sort=name> breaks for duplicate names

### ISSUE THREAD

**Issue by icemac** [zopefoundation/DocumentTemplate#17]
Scenario:

```python
list_of_dicts = [{'name': 'a'}, {'name': 'b'}, {'name': 'a'}]
```

In DTML call:

```
<dtml-in list_of_dicts mapping sort=name>
```

It breaks because internally `dtml-in` changes the list to

```python
[('a', {'name': 'a'}), ('b', {'name': 'b'}), ('a', {'name': 'a'})]
```

There is no problem as long as the list does not contain duplicates of the sort key. If there are duplicates, Python has to compare the dicts when sorting. This works fine on Python 2 but it is no loner defined on Python 3.

**Comment by pbauer** [comment]
The Error is `TypeError: '<' not supported between instances of 'dict' and 'dict'`

Comparing dicts (and thus sorting of lists of dicts) does not work in python3 without a key to sort by.
The easy solution is to pass a key (if you know the dict you are dealing with).

**Comment by pbauer** [comment]
See https://github.com/zopefoundation/Zope/pull/260 and https://github.com/zopefoundation/DocumentTemplate/pull/18
