### ISSUE TITLE
Use a pure Python implementation

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/DocumentTemplate#2]
I've started a branch (https://github.com/zopefoundation/DocumentTemplate/tree/pure-python) to replace all C code with a pure Python implementation. This should make it much easier to debug the str/unicode related issues while porting to Python 3.

A Python implementation is going to be slower than the C code. But speed shouldn't really matter anymore for DTML. If someone is interested in speed, page templates based on Chameleon are a better option. Or one could run all of Zope under PyPy in the future.

**Comment by pbauer** [comment]
🍺

**Comment by hannosch** [comment]
I've finished a first Python implementation passing all tests inside the project. So far this is only tested under Python 2. Next step is more integration testing against other projects and than porting to Python 3.

**Comment by hannosch** [comment]
I've merged the work to master. It passes all Zope tests and browsing (what's left of) the ZMI all seems to work.

I'll consider the major work to be done, if we find bugs we can file those as separate issues. Python 3 compatibility work is blocked on dependencies (AccessControl/RestrictedPython).
