### ISSUE TITLE
Changed behavior in acquisition

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/DocumentTemplate#38]
When trying to port a Zope installation from Zope2 to Zope4, I encountered an error where I am not sure if the behavior is intended and was broken in Zope2 or if it is a regression.

I could reproduce the problematic behavior with DTML Method, DTML Document as well as Z SQL Methods.

The minimal setup looks like this:

    /
    /main/
    /main/test (DTML Method containing <dtml-var included>)
    /side/
    /side/included (p.e., Python Script returning 1)

Expected behavior, working with Zope2:
Either by calling `/side/main/test` or `/main/side/test`, the content or result of `included` is found in the acquisition context and included in `test`.

Found behavior in Zope4:
Only `/main/side/test` gives the expected result, `/side/main/test` gives the attached `KeyError`

[traceback.txt](https://github.com/zopefoundation/DocumentTemplate/files/2705889/traceback.txt)

**Comment by viktordick** [comment]
By stepping through the corresponding codes, a difference I found is that in `DT_String.py` in `String.__call__` the parameter `client` is a

    <Folder at /main used for /side>

in Zope2 while it is a tuple tuple in Zope4:

    (<Folder at /main used for /side>, <DTMLDocument at /main/show>)

However, this should not be a problem since either `client.included` or `client[0].included` gives the object in `/side/included`, so in both cases it can be found. However, before `client` or `client[0]` is pushed to `md` (where names are searched later), they are plugged into `InstanceDict`. The result of

    InstanceDict(client, md)['included']

in Zope2 gives the required object, but

    InstanceDict(client[0], md)['included']

In Zope4 gives a `KeyError`

**Comment by viktordick** [comment]
The problem seems to be in `_DocumentTemplate.py` in line 311 in `3.0b5`:

    result = get(aq_inner(self.inst), key)

compared to line 88 in `2.13.4`:

    try: r = get(inst, key)

It seems the additional `aq_inner` is the key.

The origin of this change is 3f01b2fbe72fc626417f45f3cd8376a4324dbafd.

**Comment by viktordick** [comment]
If I remove the `aq_inner`, The problem described in https://github.com/zopefoundation/Zope/issues/292 reappears.

Can anyone say if this is a regression introduced by fixing that issue or if we were taking advantage on a quirk that never was supposed to work?

**Comment by viktordick** [comment]
@icemac, any thoughts on this? The fix in zopefoundation/Zope#292 was from you, after all.

**Comment by viktordick** [comment]
@icemac, any thoughts on this? The fix in zopefoundation/Zope#292 was from you, after all.

**Comment by icemac** [comment]
@viktordick I found another difference between 2.13 and 3.0: `InstanceDict` used to store the instance object on an attribute named `self`, see: https://github.com/zopefoundation/DocumentTemplate/blob/2.13/src/DocumentTemplate/pDocumentTemplate.py#L55-L56

Maybe this could be the trick to get rid of `aq_inner`.

**Comment by viktordick** [comment]
Hm with this change I can confirm that a) Acquisition works again as expected and b) User defined roles also show up in sub objects.
However, the test that was written to make sure #292 stays fixed now breaks (`DocumentTemplate.tests.test_DocumentTemplate.InstanceDictTests`). I don't completely understand yet what the test actually does and how to fix it to test the actual problem.

**Comment by viktordick** [comment]
Ok I got a weird error down the line if trying this fix. This only seems to occur if a PythonScript is called from inside a DTML method (maybe it does not have to be a PythonScript, but that's what I tested it with). If stopping with the debugger inside of the PythonScript and printing `context`, I get

    (Pdb) pp context
    <OrderedFolder at /A/B>

which is correct. However, if checking `context.aq_parent`, I get

    (Pdb) pp context.aq_parent
    InstanceDict(<OrderedFolder at /A/B>)

instead of

    (Pdb) pp context.aq_parent
    <Folder at /A>

which I get without this change. This has the consequence that I can not simply call `context.aq_parent.myprop` to read out the property `myprop` of the parent of the context, which was possible in Zope 2.13.

**Comment by d-maurer** [comment]
viktordick wrote at 2019-2-18 11:35 -0800:
>Ok I got a weird error down the line if trying this fix. This only seems to occur if a PythonScript is called from inside a DTML method (maybe it does not have to be a PythonScript, but that's what I tested it with). If stopping with the debugger inside of the PythonScript and printing `context`, I get
>
>    (Pdb) pp context
>    <OrderedFolder at /A/B>
>
>which is correct. However, if checking `context.aq_parent`, I get
>
>    (Pdb) pp context.aq_parent
>    InstanceDict(<OrderedFolder at /A/B>)
>
>instead of
>
>    (Pdb) pp context.aq_parent
>    <Folder at /A>
>
>which I get without this change. This has the consequence that I can not simply call `context.aq_parent.myprop` to read out the property `myprop` of the parent of the context, which was possible in Zope 2.13.

It is strange that an `InstanceDict` is in the acquisition context
of an object. I do not think that this should be the case.

However, you can use `context.aq_inner.aq_parent.myprop` to nevertheless
get the `myprop` property of the parent.

**Comment by icemac** [comment]
@viktordick I found a solution which solves both use cases and keeps the tests running, see #40.
