### ISSUE TITLE
Drop BBB code

### ISSUE THREAD

**Issue by icemac** [zopefoundation/DocumentTemplate#42]
There are modules with 0% test coverage containing only BBB imports. These can be dropped for Zope 5 aka version 4.0 of DocumentTemplate.

**Comment by icemac** [comment]
Maybe we need DeprecationWarnings for Zope 4.

**Comment by dataflake** [comment]
In 20d91c60ba5b0d1f6a562b55db07fe1724b934f0 I added a lot of `DeprecationWarnings` for obsolete modules or backwards-compatibility imports.

**Comment by icemac** [comment]
@dataflake Thank you for adding the deprecation warnings.

**Comment by dataflake** [comment]
The only thing I didn't like was the naming convention `DocumentTemplate._DocumentTemplate` that had to do with the historic split between `cDocumentTemplate` and `pDocumentTemplate`. At some point I'd like to rename that `_DocumentTemplate` module to just `DocumentTemplate`.
