### ISSUE TITLE
Error in ZSQLMethod with json fields

### ISSUE THREAD

**Issue by yurij7070** [zopefoundation/DocumentTemplate#48]
In latest version of DocumentTemplate and ZSQLMethod symbol '"' is escaping in dtml-sqlvar statement. And it produce errors in ZSQLMethod with json string in <dtml-sqlvar ... type=string> as a value for field type json.
For example, create ZSQLMethod with one argument named "arg" and body:
select <dtml-sqlvar arg type=string>::json
Then click "Test", type {"a": "1", "b": "2"} in field "arg" and submit. Will be an error
invalid input syntax for type json СТРОКА 1: select '{\"a\": \"1\", \"b\": \"2\"}'::json
There was no such error in the previous version of DocumentTemplate and ZSQLMethod.

**Comment by jugmac00** [comment]
Hi @yurij7070, I transferred your issue to the DocumentTemplate project, as it is very likely that you reported problem is a regression from the recent security fix.

Maybe you could also report both your used Zope and DocumentTemplate versions, as currently both Zope 4 and Zope 2.13 are supported.

**Comment by yurij7070** [comment]
Hi @jugmac00 
We use Zope version 4.1.3 and DocumentTemplate version 3.1

**Comment by dataflake** [comment]
@yurij7070 The change to quoting was made in order to improve protection against SQL injection attacks. We have added more characters to the escaped charecter list with guidance from e.g. https://en.wikipedia.org/wiki/SQL_injection#Escaping. Specifically, we are escaping ` double quote character `"` as well now.

You can see what the code does now here: https://github.com/zopefoundation/DocumentTemplate/blob/20d91c60ba5b0d1f6a562b55db07fe1724b934f0/src/DocumentTemplate/DT_Var.py#L522-L568.

**Comment by yurij7070** [comment]
Escaping of double quotes gives wrong results, at least with PostgreSQL.
For example, create ZSQLMethod with parameter "f" and body:
create table if not exists tmp (f text);
insert into tmp values (<dtml-sqlvar f type=string>);
select * from tmp;
And when we test it, we get
GmbH \"Jet\"
Backslash remains in the data, it is not correct

**Comment by d-maurer** [comment]
I fear the new escaping implementation works well only for `MySQL` (the Wikipedia article at its base contained an escaping function for this database). From Postgres 9.1 on, Postgres no longer recognizes backslash escapes in regular strings (unless `standard_conforming_strings` is set to `off`). The reason for this is that the SQL standard knows as the only escaping mechanism the doubling of the corresponding character - but no backslash escapes. I conclude that SQL quoting needs to be database specific - with different quoting rules depending on the escape support by the database.

**Comment by dataflake** [comment]
It works for MySQL/MariaDB and most likely for SQL server, their documentation explicitly shows examples using backslash-escaping for double quotes. I'll do some manual exprimenting on PG today.

Experimenting on MariaDB tell me that you cannot "double up" the double quote character to escape it on those servers. It will end up as two literal double quotes in the text.

A compromise may be to leave the double quote character alone and don't quote it at all.

**Comment by dataflake** [comment]
I just created #49 to exclude any double quote escaping.

This change won't break any of the SQL-related DTML tags from ZSQLMethods because they explicitly suround the return value with single quotes. Only those users who use the `sql_quote` modifier in a `dtml-var` must be careful - the `dtml-var` won't surround the return value with any quotes. If a user surrounds it with double quotes he may lose.

**Comment by mauritsvanrees** [comment]
I can confirm that in Postgres double quotes end up in the text.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-2-3 06:15 -0800:
>It works for MySQL/MariaDB and most likely for SQL server, their documentation explicitly shows examples using backslash-escaping for double quotes. I'll do some manual exprimenting on PG today.
>
>Experimenting on MariaDB tell me that you cannot "double up" the double quote character to escape it on those servers. It will end up as two literal double quotes in the text.

Using double quotes for strings is not supported by the SQL standard
nor Postgres at all. Double quotes can be used (at least in Postgres;
I have no access to recent SQL standards) to quote SQL identifiers.
Postgres uses doubling double quotes to obtain a single double quote
in this case.

>A compromise may be to leave the double quote character alone and don't quote it at all.

Maybe, we can restrict (via documentation) the use of `sqlvar` (and
friends) to SQL standard conform (i.e. '...' delimited) string literals
and protect only for this case? All other uses (e.g. using `sqlvar` for
table names, identifiers or conditions) would be unprotected.

**Comment by dataflake** [comment]
DocumentTemplate 3.2.1 is now out which no longer quotes `"`, and Products.ZSQLMethods 3.0.12 is released, which depends on DocumentTemplate 3.2.1 (as do Zope `master` and `4.x`) now.

Like I said, `sqlvar` already does the right thing by enclosing the result of calling `sql_quote` with single quotes. The only case where people could run into issues is if they do a simple `dtml-var` with the `sql_quote` modifier and then enclose the result in double quotes. A rare case I would guess.

**Comment by yurij7070** [comment]
I am sorry, but the same history with doubling backslashes.
If insert 'GmbH \\"Jet\\"' by <dtml-sqlvar f type=string>, getting value 'GmbH \\\\"Jet\\\\"' in table.

**Comment by dataflake** [comment]
Backslashes must be doubled because they have special meaning in Python. The incoming value you are inserting makes no sense. You do not need the backslashes there at all.

**Comment by yurij7070** [comment]
Backslashes important for json fields. Real life example:
'{"CardType": "MasterCard", "Issuer": "JOINT STOCK COMPANY \\"ALFA-BANK\\""}'::json - correct value
But now \<dtml-sqlvar f type=string\> makes '{"CardType": "MasterCard", "Issuer": "JOINT STOCK COMPANY \\\\"ALFA-BANK\\\\""}'::json which produce error in PostgreSQL.
'{"CardType": "MasterCard", "Issuer": "JOINT STOCK COMPANY "ALFA-BANK""}'::json also produce error.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-2-4 04:09 -0800:
>Backslashes must be doubled because they have special meaning in Python.

Why should `sql_quote` have a need to double backslashes for *Python* use?
Its task is to quote (I would say a string literal) for use
in SQL. Thus, is should do something with a backslash only if
the database would otherwise misinterpret the backslash.
In particular, it must not affect a backslash for a database
which does not support backslash escapes in its string literals
(such as Postgres from version 9.1 onwards; and databases
which strictly follow the SQL standard).

I am aware that this is difficult to achieve in `DocumentTemplate`
(which does not know anything about the underlaying database system).
Maybe, its `sql_quote` should get deprecated. As a replacement,
the "database adapter" could provide a database specific
quoting method.

>The incoming value you are inserting makes no sense. You do not need the backslashes there at all.

Why should it have no sense to have a backslash as part of a value
stored in the database? Think, e.g., of a Windows filesystem path.

**Comment by dataflake** [comment]
The `sql_quote` in DocumentTemplate can't go away, it's used for `dtml-var` with `sql_quote`.

The connectors have a method named `sql_quote__` which is used for all ZSQLMethod-specific tags. The base class implementation in `Shared.DC/ZRDB.Connection.Connection` just uses the DocumentTemplate code. So yes, the connectors themselves need to override `sql_quote__` if the database has special quoting conventions.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-2-4 10:28 -0800:
>The `sql_quote` in DocumentTemplate can't go away, it's used for `dtml-var` with `sql_quote`.
>
>The connectors have a method named `sql_quote__` which is used for all ZSQLMethod-specific tags. The base class implementation in `Shared.DC/ZRDB.Connection.Connection` just uses the DocumentTemplate code. So yes, the connectors themselves need to override `sql_quote__` if the database has special quoting conventions.

We could still discuss what is considered "special":
"special" could e.g. be anything deviating from the SQL standard
(i.e. minimal quoting) or anything deviating from "MySQL" (quite
extensive quoting).

**Comment by dataflake** [comment]
From reading up on the details more it's obvious that character escaping is indeed very database-specific and especially MariaDB/MySQL allow/require a lot of escaping whereas PostgreSQL doesn't seem to want much more than single quotes escaped.

@mauritsvanrees Applying more escaping in DocumentTemplate requires very careful handling and I will note the original  PloneHotfix20200121 will also break PostgreSQL. The DocumentTemplate implementation needs to be defused. You may consider a new hotfix as well, the current one will cause problems.

As Dieter says, the database-specific quoting is a job for the database adapter maintainers, not for Zope maintainers. (Side note: I am a maintainer of Products.ZMySQLDA, so I can fix that at least).

**Comment by dataflake** [comment]
I published a new round of releases for DocumentTemplate and Products.ZSQLMethods. Give it a try.

**Comment by yurij7070** [comment]
I did some tests with PostgreSQL, everything is fine. Thank you.

**Comment by dataflake** [comment]
Thanks, calling this closed then. All further work must be done at the database adapter level.
