### ISSUE TITLE
TreeDisplay error (TreeTag.py)

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/DocumentTemplate#52]
I just patched the ZSQLite Adapter for Python 3 and run into the following error when accessing the "Browse" tab of the adapter:

    File "/my/zope/installation/lib/python3.8/site-packages/TreeDisplay/TreeTag.py", line 416, in tpRenderTABLE
    nowrap = (args['nowrap'] and ' style="white-space: nowrap"') or ''
    KeyError: 'nowrap'

The line in question was quite easy to patch:

    nowrap = (args.get('nowrap') and ' style="white-space: nowrap"') or ''

But the underlying error is somewhere else, as args is a dictionary passed to tpRenderTABLE, so maybe it would be better to ensure that the nowrap key is always present in this dictionary.

**Comment by dataflake** [comment]
I moved the issue where the code in question actually resides.

**Comment by georgpfolz** [comment]
@dataflake sorry, I suspected I was posting in the wrong location but couldn't figure out where it belongs...

**Comment by dataflake** [comment]
I just published version 3.2.3, which fixes the issue.
