### ISSUE TITLE
bytes_sql_quote() returns Bytes, although the content will be part of an SQL query String

### ISSUE THREAD

**Issue by jan-jockusch** [zopefoundation/DocumentTemplate#54]
In `DocumentTemplate/DT_Var.py`, the helper function `bytes_sql_quote()` is used to remove dangerous content from Bytes when used in SQL queries (edited after correction from @dataflake).

Because this escaped content is returned as Bytes, not String, it is impossible to correctly quote Bytes with `<dtml-sqlvar xy type="string">`, because the two cannot be concatenated.

This patch works for us:

    *** zope4_orig/lib/python3.8/site-packages/DocumentTemplate/DT_Var.py	2020-06-24 08:48:39.767829123 +0200
    --- zope4/lib/python3.8/site-packages/DocumentTemplate/DT_Var.py	2020-06-24 11:06:30.294957406 +0200
    ***************
    *** 534,540 ****
          # Double untrusted characters to make them harmless.
          for char in DOUBLE_BYTES:
              v = v.replace(char, char * 2)
    !     return v

      def text_sql_quote(v):
    --- 534,544 ----
          # Double untrusted characters to make them harmless.
          for char in DOUBLE_BYTES:
              v = v.replace(char, char * 2)
    !     # We return a string because the quoted material will be
    !     # concatenated with other strings to form the query.
    !     # If the eighth bit is set, we interpret as UTF-8, just
    !     # because that encoding is to amazingly popular...
    !     return v.decode('utf-8')

      def text_sql_quote(v):

**Comment by jan-jockusch** [comment]
It would be just as good to place the encoding in the outer function `sql_quote()`.

The chosen encoding, `'utf-8'`, comes out of the blue here. Binary escaped SQL should really be 7-bit-content, but this code does not ensure that.

**Comment by d-maurer** [comment]
Ján Jockusch wrote at 2020-6-29 00:07 -0700:
>It would be just as good to place the encoding in the outer function `sql_quote()`.
>
>The chosen encoding, `'utf-8'`, comes out of the blue here. Binary escaped SQL should really be 7-bit-content, but this code does not ensure that.

If the binary data is really a sequence of bytes (rather than
encoded text),
you should use "latin-1" (rather than "utf-8") because
that is the natural mapping between a byte sequence and a unicode string.

Note that database systems usually require special means to
add truely binary data: usually, you cannot have binary data in
SQL strings.

**Comment by jan-jockusch** [comment]
Well, it depends, no? Both MS-SQL and PostgreSQL have a  syntax for correctly escaping binary content as a 7-bit string.

The string generated here is actually further processed by DTML into a String which is then sent to the database using the currently set client encoding (which can be anything, really).

So, the encoding choice here is really more about the encoding in Zope4, than about the client encoding of the database.

The typical encoding used in Zope4 nowadays seems to be `utf-8`, with 350 ocurrences in the code versus 80 for `latin-1` or `iso-8859-1`. There is no default configuration in `zope.conf`, so I cannot pick that value.

In principle, we might as well use `latin-1` or even `ascii` here, because If you really send Bytes into `<dtml-sqlvar type="string">`, they should not have the 8th bit set.

My choice of `utf-8` is directed by the popularity of the encoding in Zope4, and I would count on the python database modules called by ZSQL Methods to use the correct client encoding.

In this way, this patch solves the 98% problem of someone accidentally forgetting to encode strings correctly before using them in `<dtml-sqlvar type="string">`. At least in the case of a utf-8 encoded web application.

Do you have `latin-1` encoded apps in the field? Then we should talk about how to make this configurable.

**Comment by dataflake** [comment]
I think there's a misunderstanding about what those functions are there for. They are not "designed to produce correctly quoted strings for representing binary content in SQL". All they do is remove or escape certain characters that may break the query or that are potentially harmful.

**Comment by jan-jockusch** [comment]
OK, then the place where the encoding should be done is further up in the call stack, in DTML / ZSQL Methods?

Because no matter what the intention, the problem is definitely there. If not here, I need to fix the issue elsewhere.

**Comment by dataflake** [comment]
You haven't really provided any details about the actual problem so I have no idea.

**Comment by jan-jockusch** [comment]
Sorry. We're in the middle of rolling out Zope4, and I confused our internal discussions on this topic with this one.

This is the full scenario, then:

A large Zope2 application with code contributed from many developers, code base partially very old, uses ZSQL Methods profusely.

This includes the use of `<dtml-sqlvar something type="string">` or `<dtml-sqlvar something type="nb">`.

This application is to be migrated to Zope4, if possible not having to rework the whole codebase.

Because Zope2 uses 8bit Strings in DTML, a lot of code in the application may erroneously send Bytes into DTML after the migration to Zope4.

We have been able to upgrade large applications successfully by going this deep and patching `sql_quote()`. For us, this was a good place to patch, because other tools, apart from ZSQL Methods, also use `sql_quote()` with the same errors.

Since we use a patched version of Zope4 anyway, we can live without this patch in the mainline. We just thought that maybe other people face the same challenges, and wanted to contribute this approach to solve at least one of the many encoding issues.

If there's a problem with this method, I'm willing to look for a better way. This is not about complaining, but about contributing.

**Comment by dataflake** [comment]
As someone who has gone through a similar migration of a very old and large database-driven Zope 2 application that also uses ZSQL methods all over the place I have not seen `sql_quote` being a problem. Like I said before, `sql_quote` would be the wrong place for a change like that, anyway, because it exists for a different purpose.

In our migration we made sure all inputs are correct before they hit the ZSQL methods. Every application is different, but for us that was doable and we thought it the cleanest approach. I would always recommend that first.

The only big item for us was switching the relational database from the old Latin-1 default character set to UTF-8 and migrating all data in text/string columns. That way we have a clean stack that uses UTF-8 throughout, which made intermittent issues with text input copied and pasted from e.g. MS Word disappear as well.

**Comment by jan-jockusch** [comment]
I agree completely that cleaning up the application is the best approach. We did that for the core components of our applications.

Unfortunately, we have many applications out there and they have been partially altered by customers, so we have no real control over the code prior to doing an upgrade to Zope4. In that light, we need to make the transition as smooth as possible, which also means we "auto-correct" input values in a very non-Python3 way at times.

You're obviously better off. Your application is already clean enough never to send Bytes into `sql_quote()` anyway. Therefore, your code never even uses `bytes_sql_quote()`, if I'm not mistaken? Because if it did, you'd have seen the same error we got: That `str`and `bytes` cannot be concatenated.

But what good is `bytes_sql_quote()`, then? If I call it to quote dangerous material from Bytes, like duplicating quotes, but cannot concatenate the result with the rest of my query afterwards, it is of no real use to me. As it stands, `sql_quote()` does not consistently return something compatible with `str` (which it did in Python2).

Seen this way, the above patch does not affect anyone with a clean application, because the affected function will never be executed. Or is it possible to call `<dtml-sqlvar>` from a DTML source that is in Bytes? That would be the only possibility to call `bytes_sql_quote()` without error.

**Comment by dataflake** [comment]
`bytes_sql_quote` applies quoting to bytes values, period. It is neither `bytes_sql_quote` not `sql_quote`'s job to convert between bytes and string or vice versa and making them do so in this central place seems way too risky to just bang it in there, so I do not want to do it.

**Comment by jan-jockusch** [comment]
That's a fair objection.

I'll go back and try to find a better way to solve this issue. If it is totally meaningless to the rest of the community, feel free to close.

**Comment by dataflake** [comment]
Meaningless is the wrong word. It just hasn't come up in the way you describe.

Just as food for thought: There's actually one argument to make in favor of making `sql_quote` at least return a native string. I was looking at the implementations for all the other modifier keys you can use with `dtml-var` and even though there's no written specification for what those modifiers should accept and return their implementations imply both input and output are native strings. I don't recall right now why the bytes variety was added, though.

**Comment by dataflake** [comment]
@mauritsvanrees Do you remember why you changed the behavior of `sql_quote` to allow it to return bytes in https://github.com/zopefoundation/DocumentTemplate/commit/91b390784302efc438c07ddd74111866fa7fe5b7? Prior to that it used the same implied "only works with/returns native strings" standard that all the different modifier functions appear to use.

**Comment by mauritsvanrees** [comment]
From what I remember, this was needed to make this function work on both Python 2 and 3, without getting errors when comparing bytes and unicode. I am not sure if I actually saw such errors (except in tests) or if this was just a precaution.

I don't think we can be 100 percent sure that we always get a native string as input. Even if DocumentTemplate itself does the right thing, someone may import it and use it with unicode on Python 2 or bytes in Python 3. `Products.ZSQLMethods` [uses it](https://github.com/zopefoundation/Products.ZSQLMethods/blob/303db99ca07b12153eb195af090bf93a212fe39d/src/Shared/DC/ZRDB/Connection.py#L214). I have no idea if we can guarantee that the value there is always a native string.

If you have two items that might be bytes or unicode (to use those terms) and you rely on `sql_quote` to turn them both into native strings, that feels wrong to me. If this has worked so far, to me it feels like a happy accident, although I guess it may have been a deliberate design decision.

**Comment by dataflake** [comment]
The main issue isn’t what the function accepts, but what it returns. It used to return native strings only - as do all those modifier functions. It may make sense to restore that part of the behavior or designate a separate implementation that is used for dtml-var only and always returns native strings for the tag.

**Comment by jan-jockusch** [comment]
Thanks, guys, for the helpful thoughts and input!

It's really all about the transition from Python 2 to Python 3, keeping the old behaviour as much as possible. This is especially difficult with DTML, because it used bytes, not unicode (I'll stick to these terms, too) for internal storage. When contatenating unicode and bytes, Python 2 elevated the type automatically, producing all those well-known umlaut artifacts.

I realize that we don't want to keep the broken behaviour, and the unchanged `bytes_sql_quote()` works fine (i.e., it is never called) in a setting where all input is unicode. And that is really what it always should be: Even when passing binary material, we have to escape the binary content according to the specification of the respective database backend (octal literals in PostgreSQL, hex literals in MS-SQL, and whatever Oracle uses), so we have to do it in advance anyway, passing the escaped unicode to `sql_quote()`.

The comment in my patch should really read: "Patch the otherwise rarely if ever used 'bytes_sql_quote()' to save accidentally passed bytes content from raising an error". Actually, the conversion may just as justifiably be made in `sql_quote()`.

That would definitely change the function's meaning from "quote dangerous material, keeping the type" into "quote dangerous material and prepare to be concatenated to unicode, which must provide the outer single quotes". But since whoever calls this function must provide the quotes and the enclosing query anyway, we are really always talking about unicode (or native string) output.

Ironically, I really should have made a similar patch for Zope 2.13. We had many situations in which we deliberately had to convert unicode into bytes before using the material in DTML, because the DTML source was in bytes. This same patch would have saved us a lot of trouble back in the day… the situation was the exact opposite of what we see today, which is why so much legacy code we see now passes bytes into DTML.

**Comment by dataflake** [comment]
@mauritsvanrees Take a look at #55 and let me know what you think. Is there any testing you can use in a Plone context to take it through its paces?

**Comment by jan-jockusch** [comment]
The PR really simplifies things a lot. I'll put the new version of `DT_Var.py` into our development installation just to confirm it works for us. But it really should, the tests all look fine.

Thank you both, very much, for this effort!

**Comment by dataflake** [comment]
I just released DocumentTemplate version 3.3 with this fix.
