### ISSUE TITLE
version compatibility?

### ISSUE THREAD

**Issue by lsloan** [zopefoundation/DocumentTemplate#9]
* Is this DocumentTemplate 3.0a2 based on the DocumentTemplate 3.4.3 code mentioned in PyPI (https://pypi.python.org/pypi/zope.documenttemplate)?
* Would DTML written to work with DocumentTemplate 1.2 from the old Zope web site work with the recent releases of DocumentTemplate from this repo?

**Details:**
I've received a request to update an old app that uses DocumentTemplate.  It was extracted from Zope along with some other Zope modules it required.  It runs without Zope itself, as far as I can tell. 
 It appears to be DocumentTemplate version 1.2.

PS: I'm glad this project exists and has been active recently.

**Comment by hannosch** [comment]
I'm not sure about compatibility between version 1.2 and 3.0a2, you just have to try. But there's a good chance it works, as the DTML language spec / syntax hasn't really changed over the years.

zope.documenttemplate is an unrelated new implementation of the same language spec. It might work or it might not, but I would ignore it if you are upgrading from an old DocumentTemplate version. This project is an extract of what used to be shipped as part of the Zope2 project.

**Comment by lsloan** [comment]
👍 Thanks for the info @hannosch.  This seems to be good news.  I'll give it a try and if I notice any major problems, I'll open a new issue here.

It'll be great if this works.  I won't need to worry about changing a lot of code that calls DocumentTemplate and a lot of DTML to work with some other templating module.

Can you tell me where to find documentation of the language spec?

**Comment by hannosch** [comment]
For docs, the ones over at https://docs.zope.org/zope2/zope2book/DTML.html might still be accurate. There's also https://docs.zope.org/zope2/zope2book/AdvDTML.html and https://docs.zope.org/zope2/zope2book/AppendixA.html.
